In [1]:
import numpy as np
import matplotlib.pylab as plt
import matplotlib

In [ ]:
a = np.array([1, 2, 3, 4, 5, 8, 100])

a, a.shape


(array([  1,   2,   3,   4,   5,   8, 100]), (7,))

In [ ]:
b = np.array([[1, 2, 3, 2], [4, 5, 6, 20], [7, 8, 9, 10]])

b, b.shape, b[0:3, 1:2]

array([[ 1,  2,  3,  2],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 10]])

In [ ]:
c = np.arange(1, 21)

c, c.reshape(4, 5), c.mean(), c.max(), c.min()

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]))

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(-10, 11)
y = 2 * x + 3  # persamaan y = 2x + 3

plt.plot(x, y)
plt.title("Grafik Fungsi Linear")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)
plt.show()


In [6]:
angka = np.arange(1, 31).reshape(5, 6)

baris_ketiga = angka[2, :]
kolom_kedua = angka[:, 1]

rata_rata = angka.mean()
maksimum = angka.max()
minimum = angka.min()

angka, baris_ketiga, kolom_kedua, rata_rata, maksimum, minimum

(array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]]),
 array([13, 14, 15, 16, 17, 18]),
 array([ 2,  8, 14, 20, 26]),
 np.float64(15.5),
 np.int64(30),
 np.int64(1))